# Sidebar navigation

- label: เกี่ยวกับเรา
  link: /
- label: Net MD
  items:
    - label: คู่มือติดตั้งและใช้งานโปรแกรม SonicStage
      link: /net-md/sonic-stage-manual
    - label: คู่มือใช้งาน Web MiniDisc
      link: /net-md/web-mini-disc-manual
    - label: คู่มือติดตั้งและใช้งานโปรแกรม MD Simple Burner
      link: /net-md/md-simple-burner-manual

    - label: รู้จัก MD recording mode
      link: /net-md/md-recording-mode
    - label: ทดสอบเวลาที่ในการเขียนเพลง MP3 ลงแผ่น MD
      link: /net-md/writing-disc-time-usage-test
    - label: ชื่อรุ่นของ Sony MD players
      link: /net-md/md-player-model-number
    - label: รีโมทรุ่นต่างๆ ของ Sony MD
      link: /net-md/sony-md-remotes

    - label: MD head-lens cleaner
      link: /net-md/md-head-lens-cleaner

- label: Useful resources
  items:
    - label: Yahoo Auction Japan calculator
      link: /useful-resources/yahoo-auction-japan-calculator
