# Sidebar navigation

- label: เกี่ยวกับเรา
  link: /
- label: Net MD
  items:
    - label: เริ่องเล่า MiniDisc
      link: /net-md/mini-disc-story

    - label: คู่มือติดตั้งและใช้งานโปรแกรม SonicStage
      link: /net-md/sonic-stage-manual
    - label: คู่มือใช้งาน Web MiniDisc
      link: /net-md/web-mini-disc-manual
    - label: คู่มือติดตั้งและใช้งานโปรแกรม MD Simple Burner
      link: /net-md/md-simple-burner-manual

    - label: รู้จัก MD recording mode
      link: /net-md/md-recording-mode
    - label: ทดสอบเวลาที่ในการเขียนเพลง MP3 ลงแผ่น MD
      link: /net-md/writing-disc-time-usage-test
    - label: ชื่อรุ่นของ Sony MD players
      link: /net-md/md-player-model-number
    - label: รีโมทรุ่นต่างๆ ของ Sony MD
      link: /net-md/sony-md-remotes

    - label: MD head-lens cleaner
      link: /net-md/md-head-lens-cleaner
    - label: ข้อดีของ Net MD
      link: /net-md/advantages-of-net-md
    - label: Sony Net MD decks
      link: /net-md/sony-net-md-decks

- label: Useful resources
  items:
    - label: รวม Wiki ข้อมูลของเครื่องเล่นแบบต่างๆ
      link: /useful-resources/audio-player-wiki
    - label: Interesting players with VU meters
      link: /useful-resources/interesting-players-with-vu-meters
    - label: Handmade reel to reel cassette tape
      link: /useful-resources/handmade-reel-to-reel-cassette-tape

    - label: MD player parts
      link: /useful-resources/md-player-parts
    - label: Adjustable metal headband on-ear headphones (ก้านเหล็ก)
      link: /useful-resources/adjustable-metal-headband-on-ear-headphones

    - label: Yahoo Auction Japan calculator
      link: /useful-resources/yahoo-auction-japan-calculator
